#!/bin/sh

BACKUP_BASE=./
BACKUP_CONF=$BACKUP_BASE/example.conf
BACKUP_DIR=$BACKUP_BASE/backups
BACKUP_CMD=$BACKUP_BASE/../rsyncbackup.py
BACKUP_SERVER=backup01
BACKUP_USER=root
BACKUP_NS=backup-name
BACKUP_KEEP=90

$BACKUP_CMD --server $BACKUP_SERVER -c $BACKUP_CONF -t $BACKUP_DIR -u $BACKUP_USER -n $BACKUP_NS -k $BACKUP_KEEP